Feature/auth page structure
assist-software/academy-hove-app pull request #28
Opened 2022-08-24 14:58 UTC by florin-baciu

- added all the elements for the signup-login pages (more styling required later)

2022-08-25 11:42 UTC, victorjeman reviewed
Ca un comentariu general. @mariancristivrabie  @florin-baciu 
Nu trebuie sa respectam designul din Figma 100% ci mai degraba sa facem lucrurile cat mai consistente ca sa le putem refolosi prin mai multe locuri.

Spre exemplu, daca avem vreun h1 pe undeva, decidem ce font-size si margin are si dupa peste tot pe unde mai e nevoie de h1 sa fie acelasi stil.
La fel si cu alte spacing-uri. Obiectivul e sa iesim la final cu o aplicatie care e foarte consistenta din punct de vedere al organizarii componentelor si spatieri chestiilor.
Nu ne intereseaza sa iasa 100% ca-n figma in termeni de spatii, font-size, margin, etc.

2022-08-25 11:50 UTC, mariancristivrabie commented on src/features/auth/components/auth-form/auth-form.tsx
> +      {type === 'signup' && (
I think this kind of strings like `signup`, we can save them into some kind of app constants file and import it from there.

2022-08-25 11:50 UTC, mariancristivrabie commented on src/features/auth/components/auth-form/auth-form.tsx
> +          <div className={styles.authFormDivider}>
I think we can create this divider as a separate component, what do you think?

2022-08-25 11:50 UTC, mariancristivrabie commented on src/features/auth/components/auth-form/auth-form.tsx
> +        {type === 'login' && (
same here, `login`  I think it would be better to be a constant.

2022-08-25 11:50 UTC, mariancristivrabie commented on src/features/auth/components/auth-form/auth-form.tsx
> +          onClick={() => {
For better understanding, we can add the logic of buttons click into a separate function and call that function with necessary parameters.

2022-08-25 11:50 UTC, victorjeman requested changes

2022-08-25 11:50 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +import { Link } from 'react-router-dom'
`import { Link } from 'react-router-dom'`
module npm sa fie grupate impreuna.

2022-08-25 11:50 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> -    <div className={styles.authForm}>
@florin-baciu, sa incerci te rog sa foloseti abordarea de aici https://www.primefaces.org/primereact/reacthookform/ ca sa profitam de primereact cat mai mult.

2022-08-25 11:50 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +        <h1 className={styles.authFormTitle}>{type === 'signup' ? 'Create account' : 'Log in'}</h1>
Termeni precum "signup", "Create account", si toate textele care vin folosite hardcodate sa le salvam intr-un fisier in constants numit `auth-i18-constants` si de acolo sa faci un export la un obiect `AUTH_I18`cu toate cuvintele hardcodate.
**De ce?** ca sa ne pregatim usor de ideea de internationalization, adica sa putem traduce aplicatia in cel putin 2 limbi.

P.S. Nu stiu inca cum se face, dar stiu ca cu siguranta o sa avem nevoie de toate cuvintele intr-un fisier separat si may as well sa le punem de pe acum intr-un fisier constants.

cc: @mariancristivrabie

2022-08-25 11:50 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +            icon={<img alt='' src={googleLogo} />}
Mereu sa punem ceva in atl=""

2022-08-25 11:50 UTC, victorjeman commented on src/styles/login-page.module.scss
> +@import 'styles/variables.scss';
Hai sa pune fiecare pagina intr-un folder si in acel folder sa avem si styling-ul.
spre exemplu.

```
/pages/page-login/page-login.tsx
/page/page-login/page-login.module.scss
```
ca sa pastram lucrurile consistent
cc: @mariancristivrabie

2022-08-26 13:31 UTC, victorjeman requested changes

2022-08-26 13:31 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +                Log in
"Log in" cu constant

2022-08-26 13:31 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +                Sign up
"Sign up" cu constant

2022-08-26 13:31 UTC, victorjeman commented on src/features/auth/components/auth-form/auth-form.tsx
> +              Already have an account?{' '}
"Already have an account?" cu constant

2022-08-26 13:44 UTC, victorjeman submitted a review, later dismissed

2022-08-26 15:13 UTC, merged