implement-profile-components
assist-software/academy-hove-app pull request #43
Opened 2022-09-10 16:14 UTC by CostescuAdrian

SS Figma
![image](https://user-images.githubusercontent.com/108259616/189492138-244b9d63-9ca4-4c20-8827-1ffd589d13ff.png)

SS Results
![1](https://user-images.githubusercontent.com/108259616/189492146-51306f00-2a6f-4f4e-b3f8-d55c970e9ff2.JPG)
![2](https://user-images.githubusercontent.com/108259616/189492148-14aee560-7f2f-43b4-9956-ccff492ae0dd.JPG)
![3](https://user-images.githubusercontent.com/108259616/189492150-66522899-a545-4f69-91c9-970a93499129.JPG)
![4](https://user-images.githubusercontent.com/108259616/189492152-79c176a2-9cef-4fcc-88e3-2612458f09f3.JPG)

2022-09-14 13:56 UTC, florin-baciu requested changes

2022-09-14 13:56 UTC, florin-baciu commented on src/features/profile/components/profile-edit-address/profile-edit-address.tsx
> +    <div className={commonStyle.profileContent}>
Consider using this approach when you have a form [https://www.primefaces.org/primereact/reacthookform/](https://www.primefaces.org/primereact/reacthookform/ ).
The AuthForm component also uses this approach if you need some more code examples

2022-09-14 13:56 UTC, florin-baciu commented on src/features/stepper/components/stepper-navigation/stepper-navigation.tsx
> +      </div>
It seems i also implemented this in another PR ( [42-feature-|-profile-settings-page branch](https://github.com/assist-software/academy-hove-app/pull/47) ) , i think the other devs should review both of them and decide with wich one we go further

2022-09-14 13:56 UTC, florin-baciu commented on src/App.tsx
> +  // }, [])
You can delete this code , i improved the auth checking on another pr

2022-09-22 13:56 UTC, victorjeman requested changes

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/components/profile-edit-address/profile-edit-address.tsx
> +import commonStyle from '../../style/profile-style.module.scss'
nu stiu ce sa zic despre abordarea asta cu common style.
Poate am putea sa ave o componenta ce se refoloseste

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/components/profile-edit-address/profile-edit-address.tsx
> +        <div className={commonStyle.profileLabel}>
In loc sa avem common style, poate sa avem o componneta care e alcatuita doar din label, input si containerul lor.

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/components/profile-edit-birth/profile-edit-birth.tsx
> +  const handleChangeDate = (e: any) => {
merge de mutat intr-un service, coul pentru date.
De asemenea vezi ca avem dayjs, poate e mai usor sa faci conversiile folosind acea librarie.

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/components/profile-show-details/profile-show-details.module.scss
> +  display: flex;
De trecut o tura prin CSS si de vazut ce poate inlocui cu utility classes din prime flex.

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/components/profile-show-details/profile-show-details.tsx
> +    <div className={style.details}>
sa corespunda numele claselor cu numele componentelor.
Adica clasele css mereu sa inceapa cu nmele componentei.
Cel putin asa incercam sa mergem in proiectul asta.

`styles.profileShowDetails`
`styles.profileShowDetailsContent`
etc.

de folosit `styles` in loc de `style`, asa am mers cu conventia.

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/constants/profile-constants.ts
> +export const ProfilePlaceholder = {
sa mergem cu CAPS_LOOK la constante si la atributele lor.
O sa adauga in curand si o regula eslint pentru asta.

2022-09-22 13:56 UTC, victorjeman commented on src/features/profile/profile-page.tsx
> +import { ProfileEditName } from './components/profile-edit-name/profile-edit-name'
pagina de profil sa fie pusa in folderul dedicat cu pagini, "src/pages"

2022-09-22 13:56 UTC, victorjeman commented on src/features/stepper/components/stepper-navigation/stepper-navigation.tsx
> +import securityActive from '../../assets/securityActive.svg'
O sa te rog sa punem tot ce tine feature-ul stepper intr-un alt PR si sa-l scoatem din asta.
E prea mult cod mai ales ca se combina mai mult de un singur feature.

2022-09-22 13:57 UTC, victorjeman commented
@AdrianCostescu,
Am lasat cateva comentarii. Te rog sa spargem in 2 PR-uri, sunt doua features in acelasi PR si e mult prea mult cod de analizat.

Pune stepper intr-un PR si celalalt feature sa ramana in asta.
Mersi

2022-10-28 06:46 UTC, victorjeman requested changes

2022-10-28 06:46 UTC, victorjeman commented on src/features/profile/components/profile-edit-address/profile-edit-address.module.scss
> +.editAddressContent {
.profileEditAdress {}

profileEditAdressForm {}

2022-10-28 06:46 UTC, victorjeman commented on src/features/profile/components/profile-edit-birth/profile-edit-birth.tsx
> +  const handleChangeDate = (e: any) => {
De folosit day.js in loc de custom new Date object.

2022-10-28 06:46 UTC, victorjeman commented on src/features/profile/components/profile-edit-name/profile-edit-name.module.scss
> +.editNameContent {
la fel si aici cu clasele

2022-10-28 06:46 UTC, victorjeman commented on src/pages/page-user/page-user.tsx
> +// import { StepperNavigation } from 'features/stepper/components/stepper-navigation/stepper-navigation'
De sters codul daca nu e nevoie

2022-10-28 06:46 UTC, victorjeman commented on src/pages/page-user/page-user.tsx
> +export const PageUser = () => {
De sters partea cu stepper ca avem alt PR

2022-11-11 14:30 UTC, merged